default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rails_test_ci_development

test:
  <<: *default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: password
  host: localhost
  database: myapp_test


production:
  <<: *default
  database: rails_test_ci_production
  username: rails_test_ci
  password: <%= ENV["RAILS_TEST_CI_DATABASE_PASSWORD"] %>
