name: test flow # ワークフローの名前

on:
  [push] # プッシュしたらとりま実行する

jobs:
  job-name:
    runs-on: ubuntu-latest
    steps: # jobの実行内容
      - name: echo a string #job内のstepの名前
        run: echo "Hello world"
      - name: multiline script
        run: |
          node -v
          npm -v
  job-name2:
    runs-on: windows-latest
    needs: [job-name]
    steps:
      - name: directory powershell
        run: Get-Location
      - name: Directory Bash
        run: pwd
        shell: bash
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: simple JS actions
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: John
      - name: Log greeting time
        run: echo "${{ steps.greet.outputs.time }}"

# test3
