name: test flow # ワークフローの名前

on:
  [push] # プッシュしたらとりま実行する

jobs:
  job-name:
    runs-on: ubuntu-latest
    steps: # jobの実行内容
      - name: echo a string #job内のstepの名前
        run: echo "Hello world"
      - name: multiline script
        run: |
          node -v
          npm -v
