name: test flow # ワークフローの名前

on:
  [push] # プッシュしたらとりま実行する

jobs:
  job-name:
    runs-on: ubuntu-latest
    steps: # jobの実行内容
      - name: echo a string #job内のstepの名前
        run: echo "Hello world"
      - name: multiline script
        run: |
          node -v
          npm -v
  rspec:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setting up ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

# test4
